### PR TITLE
automatically fail users with passwords exceeding 4096 bytes

### PR DESCRIPTION
**Pull request by DatGuy1**
Not sure if "break" would work or what to put in place. Perhaps a goto: ?

### CODE REVIEW

**Comment by zhuyifei1999** [comment]
This check should go before the hashing. It is the expensive hashing functions such as bcrypt that requires the check to prevent DOS.

Also, what about login and/or change password?

**Comment by DatGuy1** [comment]
It does go before it. It affects the original password. Working on your latter comment. Feel free to review it. Also, this will need to be cherry-picked.

**Comment by DatGuy1** [comment]
Just noticed it'll be tricky since its on .gitignore. I'll nudge Samtar a bit.

**Comment by samtarling** [comment]
No longer required as we've migrated to OAuth

**Pull request closed without merging**
